name: monitoring
version: 0.1.0.0
github: 'githubuser/monitoring'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2020 Author name here'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/monitoring#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ekg:
    main: Main.hs
    source-dirs: app/ekg
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - monitoring
      - ekg == 0.4.0.15
  runtime:
    main: Main.hs
    source-dirs: app/runtime
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - monitoring

tests:
  foo-test:
    main: Main.hs
    source-dirs: test/foo-test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - monitoring
  bar-test:
    main: Main.hs
    source-dirs: test/bar-test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - monitoring
